config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  resources :questions do
    resources :answers
  end

  root 'dashboard#index'

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :content, presence: true, length: { minimum: 2 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  validates :content, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  validates :username, :password, presence: true, length: { minimum: 4 }
end

app/models/vote.rb
class Vote < ApplicationRecord
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def create
    @qustion = Question.find(params[:question_id])
    @answer = @qustion.answers.create(answer_params)
    redirect_to question_path(@qustion)
  end

  def Destroy
    @qustion = Question.find(params[:question_id])
    @answer = @qustion.answers.find(params[:id])
    @answer.Destroy
    redirect_to question_path(@qustion)
  end

  private
    def answer_params
      params.require(:answer).permit(:answerer, :content)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  private
    def question_params
      params.require(:question).permit(:user, :content)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<p>
  <strong>User: </strong>
  <%= answer.answerer %>
</p>

<p>
  <strong>Answer: </strong>
  <%= answer.content %>
</p>

<p>
  <%= link_to 'Destroy Answer', [answer.question, answer],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/answers/_comment.html.erb
<p>
  <strong>User:</strong>
  <%= answer.answerer %>
</p>

<p>
  <strong>Answer:</strong>
  <%= answer.body %>
</p>

<p>
  <%= link_to 'Destroy Answer', [answer.question, answer],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/answers/_form.html.erb
<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/dashboard/index.html.erb
<h1>QuestionBox</h1>
<%= link_to 'Questions', controller: 'questions' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestionBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<%= link_to 'New question', new_question_path %>
<table>
  <tr>
    <th>Questions</th>
    <th colspan="2"></th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= question.content %></td>
      <td><%= link_to 'Show', question_path(question) %></td>
      <td><%= link_to 'Edit', edit_question_path(question) %></td>
      <td><%= link_to 'Destroy', question_path(question),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h1>New Questions</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>User:</strong>
  <%= @question.user %>
</p>

<p>
  <strong>Question:</strong>
  <%= @question.content %>
</p>

<h2>Answers</h2>
<%= render @question.answers%>


<h2>Answer question:</h2>
<%= render 'answers/form' %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>